# Generated by Django 2.1.2 on 2019-09-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='views',
        ),
        migrations.AddField(
            model_name='view',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_mangement.Ad'),
        ),
        migrations.AddField(
            model_name='click',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_mangement.Ad'),
        ),
    ]
