# Generated by Django 2.1.2 on 2019-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0002_auto_20190928_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='approved',
            field=models.CharField(choices=[('PE', 'pending'), ('RJ', 'rejected'), ('OK', 'approved')], default='PE', max_length=2),
        ),
    ]
